// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parsey_api.proto

package cali.nlp;

public final class ParseyApi {
  private ParseyApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParseyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cali.nlp.ParseyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string text = 1;</code>
     */
    java.util.List<java.lang.String>
        getTextList();
    /**
     * <code>repeated string text = 1;</code>
     */
    int getTextCount();
    /**
     * <code>repeated string text = 1;</code>
     */
    java.lang.String getText(int index);
    /**
     * <code>repeated string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes(int index);
  }
  /**
   * Protobuf type {@code cali.nlp.ParseyRequest}
   */
  public  static final class ParseyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cali.nlp.ParseyRequest)
      ParseyRequestOrBuilder {
    // Use ParseyRequest.newBuilder() to construct.
    private ParseyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseyRequest() {
      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ParseyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                text_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              text_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          text_ = text_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cali.nlp.ParseyApi.ParseyRequest.class, cali.nlp.ParseyApi.ParseyRequest.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList text_;
    /**
     * <code>repeated string text = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTextList() {
      return text_;
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public java.lang.String getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes(int index) {
      return text_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < text_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < text_.size(); i++) {
          dataSize += computeStringSizeNoTag(text_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTextList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cali.nlp.ParseyApi.ParseyRequest)) {
        return super.equals(obj);
      }
      cali.nlp.ParseyApi.ParseyRequest other = (cali.nlp.ParseyApi.ParseyRequest) obj;

      boolean result = true;
      result = result && getTextList()
          .equals(other.getTextList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getTextCount() > 0) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getTextList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cali.nlp.ParseyApi.ParseyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cali.nlp.ParseyApi.ParseyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cali.nlp.ParseyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cali.nlp.ParseyRequest)
        cali.nlp.ParseyApi.ParseyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cali.nlp.ParseyApi.ParseyRequest.class, cali.nlp.ParseyApi.ParseyRequest.Builder.class);
      }

      // Construct using cali.nlp.ParseyApi.ParseyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyRequest_descriptor;
      }

      public cali.nlp.ParseyApi.ParseyRequest getDefaultInstanceForType() {
        return cali.nlp.ParseyApi.ParseyRequest.getDefaultInstance();
      }

      public cali.nlp.ParseyApi.ParseyRequest build() {
        cali.nlp.ParseyApi.ParseyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cali.nlp.ParseyApi.ParseyRequest buildPartial() {
        cali.nlp.ParseyApi.ParseyRequest result = new cali.nlp.ParseyApi.ParseyRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          text_ = text_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.text_ = text_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cali.nlp.ParseyApi.ParseyRequest) {
          return mergeFrom((cali.nlp.ParseyApi.ParseyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cali.nlp.ParseyApi.ParseyRequest other) {
        if (other == cali.nlp.ParseyApi.ParseyRequest.getDefaultInstance()) return this;
        if (!other.text_.isEmpty()) {
          if (text_.isEmpty()) {
            text_ = other.text_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTextIsMutable();
            text_.addAll(other.text_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cali.nlp.ParseyApi.ParseyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cali.nlp.ParseyApi.ParseyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTextIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          text_ = new com.google.protobuf.LazyStringArrayList(text_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTextList() {
        return text_.getUnmodifiableView();
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public int getTextCount() {
        return text_.size();
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public java.lang.String getText(int index) {
        return text_.get(index);
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes(int index) {
        return text_.getByteString(index);
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder setText(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder addText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder addAllText(
          java.lang.Iterable<java.lang.String> values) {
        ensureTextIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, text_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder clearText() {
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder addTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cali.nlp.ParseyRequest)
    }

    // @@protoc_insertion_point(class_scope:cali.nlp.ParseyRequest)
    private static final cali.nlp.ParseyApi.ParseyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cali.nlp.ParseyApi.ParseyRequest();
    }

    public static cali.nlp.ParseyApi.ParseyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseyRequest>
        PARSER = new com.google.protobuf.AbstractParser<ParseyRequest>() {
      public ParseyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ParseyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseyRequest> getParserForType() {
      return PARSER;
    }

    public cali.nlp.ParseyApi.ParseyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParseyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cali.nlp.ParseyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    java.util.List<syntaxnet.SentenceOuterClass.Sentence> 
        getResultList();
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    syntaxnet.SentenceOuterClass.Sentence getResult(int index);
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    java.util.List<? extends syntaxnet.SentenceOuterClass.SentenceOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    syntaxnet.SentenceOuterClass.SentenceOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cali.nlp.ParseyResponse}
   */
  public  static final class ParseyResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cali.nlp.ParseyResponse)
      ParseyResponseOrBuilder {
    // Use ParseyResponse.newBuilder() to construct.
    private ParseyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseyResponse() {
      result_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ParseyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result_ = new java.util.ArrayList<syntaxnet.SentenceOuterClass.Sentence>();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.add(
                  input.readMessage(syntaxnet.SentenceOuterClass.Sentence.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cali.nlp.ParseyApi.ParseyResponse.class, cali.nlp.ParseyApi.ParseyResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<syntaxnet.SentenceOuterClass.Sentence> result_;
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    public java.util.List<syntaxnet.SentenceOuterClass.Sentence> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    public java.util.List<? extends syntaxnet.SentenceOuterClass.SentenceOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    public syntaxnet.SentenceOuterClass.Sentence getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .syntaxnet.Sentence result = 1;</code>
     */
    public syntaxnet.SentenceOuterClass.SentenceOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getResultCount(); i++) {
        if (!getResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(1, result_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cali.nlp.ParseyApi.ParseyResponse)) {
        return super.equals(obj);
      }
      cali.nlp.ParseyApi.ParseyResponse other = (cali.nlp.ParseyApi.ParseyResponse) obj;

      boolean result = true;
      result = result && getResultList()
          .equals(other.getResultList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cali.nlp.ParseyApi.ParseyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cali.nlp.ParseyApi.ParseyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cali.nlp.ParseyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cali.nlp.ParseyResponse)
        cali.nlp.ParseyApi.ParseyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cali.nlp.ParseyApi.ParseyResponse.class, cali.nlp.ParseyApi.ParseyResponse.Builder.class);
      }

      // Construct using cali.nlp.ParseyApi.ParseyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cali.nlp.ParseyApi.internal_static_cali_nlp_ParseyResponse_descriptor;
      }

      public cali.nlp.ParseyApi.ParseyResponse getDefaultInstanceForType() {
        return cali.nlp.ParseyApi.ParseyResponse.getDefaultInstance();
      }

      public cali.nlp.ParseyApi.ParseyResponse build() {
        cali.nlp.ParseyApi.ParseyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cali.nlp.ParseyApi.ParseyResponse buildPartial() {
        cali.nlp.ParseyApi.ParseyResponse result = new cali.nlp.ParseyApi.ParseyResponse(this);
        int from_bitField0_ = bitField0_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cali.nlp.ParseyApi.ParseyResponse) {
          return mergeFrom((cali.nlp.ParseyApi.ParseyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cali.nlp.ParseyApi.ParseyResponse other) {
        if (other == cali.nlp.ParseyApi.ParseyResponse.getDefaultInstance()) return this;
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getResultCount(); i++) {
          if (!getResult(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cali.nlp.ParseyApi.ParseyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cali.nlp.ParseyApi.ParseyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<syntaxnet.SentenceOuterClass.Sentence> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = new java.util.ArrayList<syntaxnet.SentenceOuterClass.Sentence>(result_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          syntaxnet.SentenceOuterClass.Sentence, syntaxnet.SentenceOuterClass.Sentence.Builder, syntaxnet.SentenceOuterClass.SentenceOrBuilder> resultBuilder_;

      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public java.util.List<syntaxnet.SentenceOuterClass.Sentence> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public syntaxnet.SentenceOuterClass.Sentence getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder setResult(
          int index, syntaxnet.SentenceOuterClass.Sentence value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder setResult(
          int index, syntaxnet.SentenceOuterClass.Sentence.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder addResult(syntaxnet.SentenceOuterClass.Sentence value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder addResult(
          int index, syntaxnet.SentenceOuterClass.Sentence value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder addResult(
          syntaxnet.SentenceOuterClass.Sentence.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder addResult(
          int index, syntaxnet.SentenceOuterClass.Sentence.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends syntaxnet.SentenceOuterClass.Sentence> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public syntaxnet.SentenceOuterClass.Sentence.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public syntaxnet.SentenceOuterClass.SentenceOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public java.util.List<? extends syntaxnet.SentenceOuterClass.SentenceOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public syntaxnet.SentenceOuterClass.Sentence.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            syntaxnet.SentenceOuterClass.Sentence.getDefaultInstance());
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public syntaxnet.SentenceOuterClass.Sentence.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, syntaxnet.SentenceOuterClass.Sentence.getDefaultInstance());
      }
      /**
       * <code>repeated .syntaxnet.Sentence result = 1;</code>
       */
      public java.util.List<syntaxnet.SentenceOuterClass.Sentence.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          syntaxnet.SentenceOuterClass.Sentence, syntaxnet.SentenceOuterClass.Sentence.Builder, syntaxnet.SentenceOuterClass.SentenceOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              syntaxnet.SentenceOuterClass.Sentence, syntaxnet.SentenceOuterClass.Sentence.Builder, syntaxnet.SentenceOuterClass.SentenceOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cali.nlp.ParseyResponse)
    }

    // @@protoc_insertion_point(class_scope:cali.nlp.ParseyResponse)
    private static final cali.nlp.ParseyApi.ParseyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cali.nlp.ParseyApi.ParseyResponse();
    }

    public static cali.nlp.ParseyApi.ParseyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseyResponse>
        PARSER = new com.google.protobuf.AbstractParser<ParseyResponse>() {
      public ParseyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ParseyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseyResponse> getParserForType() {
      return PARSER;
    }

    public cali.nlp.ParseyApi.ParseyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cali_nlp_ParseyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cali_nlp_ParseyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cali_nlp_ParseyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cali_nlp_ParseyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020parsey_api.proto\022\010cali.nlp\032\030syntaxnet/" +
      "sentence.proto\"\035\n\rParseyRequest\022\014\n\004text\030" +
      "\001 \003(\t\"5\n\016ParseyResponse\022#\n\006result\030\001 \003(\0132" +
      "\023.syntaxnet.Sentence2K\n\rParseyService\022:\n" +
      "\005Parse\022\027.cali.nlp.ParseyRequest\032\030.cali.n" +
      "lp.ParseyResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          syntaxnet.SentenceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cali_nlp_ParseyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cali_nlp_ParseyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cali_nlp_ParseyRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_cali_nlp_ParseyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cali_nlp_ParseyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cali_nlp_ParseyResponse_descriptor,
        new java.lang.String[] { "Result", });
    syntaxnet.SentenceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
